### PR TITLE
ZF3 compatibility

### PR DESCRIPTION
**Pull request by thomasvargiu**
Added ZF3 compatibility

### CODE REVIEW

**Comment by maglnet** [comment]
Great, thanks, I'll check/review this in the next days!

**Comment by thomasvargiu** [comment]
@maglnet Any update on this?

**Comment by maglnet** [comment]
@thomasvargiu sorry for the late response.

I would be happy with it, if the minimum dependencies wouldn't change.
But until now, i haven't had enough time to check what causes the versions to be raised.
Could you explain what causes this?

I would accept it if the minimum ZF2 requirement is `2.4` (and PHP `5.4`) since this is a ZF2 LTS release which is used by our company in some projects and I don't want to maintain 2 different versions of this simple wrapper.
https://framework.zend.com/long-term-support

**Comment by thomasvargiu** [comment]
@maglnet Done.... I did some changes to make it compatible with ZF 2.4 and PHP >= 5.3.
The master branch is not compatible with PHP 5.3 right now, even if composer say it is.

**Comment by thomasvargiu** [comment]
@maglnet Can you tag a new release?

**Comment by maglnet** [comment]
@thomasvargiu [1.5.0](https://github.com/maglnet/MaglMarkdown/releases/tag/1.5.0), thank you for your work!

**Pull request merged**
